kind: pipeline
name: build

platform:
  os: linux
  arch: amd64

steps:
  - name: build
    pull: always
    image: golang:1.13
    commands:
      - go build -v -ldflags '-w -extldflags '-static''
    environment:
      CGO_ENABLED: 0
      GO111MODULE: on
      GOPROXY: https://proxy.golang.org

  - name: jsonnet-bundler
    pull: always
    image: golang:1.13
    commands:
      - go get github.com/jsonnet-bundler/jsonnet-bundler/cmd/jb
      - jb install
    environment:
      CGO_ENABLED: 0
      GO111MODULE: off
      GOPROXY: https://proxy.golang.org
