name: slo-libsonnet-web-${DRONE_COMMIT_SHA:0:7}
steps:
  - name: manifests
    image: quay.io/metalmatze/slo-libsonnet-web:${DRONE_COMMIT_SHA:0:7}-configuration
    commands:
      - kubectl apply -f /data/kubernetes.yaml
