name: slo_libsonnet_web
description: A web app that generates SLO recording and alerting rules for Prometheus
version: 0.0.0

environment:
  sdk: '>=2.2.0 <3.0.0'

dependencies:
  angular: ^5.3.0
  angular_forms: ^2.1.2

dev_dependencies:
  build_runner: ^1.6.2
  build_test: ^0.10.8
  build_web_compilers: ^2.1.0
